my_string = input("Напишите Ваше любимое развлечение (3 слова): ")
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string.replace(' ', '|'))
print(my_string[0])
print(my_string[-1])
print(" ")
my_string = input("Напишите Ваше имя: ")
current_year = 2024
date_of_birth = int(input("Введите Ваш год рождения: "))
age = current_year - int(date_of_birth)
email = input("Введите Ваш электронный ящик: ")
print("Здраствуйте, ", my_string, ", Вам: ", age, "лет (года), Ваш Email: ", email)
